language: go

env:
  - GOPROXY=https://cache.greedo.xeserv.us GO111MODULE=on

go:
  - "1.12"
  - "1.13"
  - "1.14"

go_import_path: within.website/ln

script:
  - LN_FORMATTER=text go test -v -race -cover ./...
